version: "3.9"

services:

  mysqldb:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_management
    ports:
      - "3307:3306"     # host:container
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 6
      start_period: 25s

  backend:
    image: pgsharshavardhan/docker-backend-project:latest
    container_name: springboot
    ports:
      - "2025:2000"     # host:container
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - springboot-mysql-net
    restart: on-failure

  frontend:
    image: pgsharshavardhan/docker-frontend-project:latest
    container_name: react
    ports:
      - "3000:80"        # host:container
    depends_on:
      - backend
    networks:
      - springboot-mysql-net
    restart: on-failure

networks:
  springboot-mysql-net:
