services:

  mysqldb:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_management
    ports:
      - "3307:3306"
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 6
      start_period: 25s

  backend:
    image: pgsharshavardhan/docker-backend-project:latest
    container_name: springboot
    ports:
      - "2025:2000"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - springboot-mysql-net
    restart: on-failure

networks:
  springboot-mysql-net:
